### ISSUE TITLE
Webhook for SimpleDeployment

### ISSUE THREAD

**Issue by mattmoor** [knative-extensions/sample-controller#487]
I noticed that SimpleDeployment was missing here: https://github.com/knative-sandbox/sample-controller/blob/e9f9f48d96f7828f829e3140f9695b1b8af98cd6/cmd/webhook/main.go#L43

Seems like it should be for the defaulting/validation to work.

cc @markusthoemmes

**Comment by swastik959** [comment]
hi @mattmoor I want to work on this issue can you guide me through it ?

**Comment by dprotaso** [comment]
@swastik959 Matt linked were the `AddressableService` webhook was setup.  That should be a template for adding `SimpleDeployment` there.
